// Copyright (c) 2026 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.

package org.cef.browser;

/**
 * Supported content setting types. Integer values are pinned to
 * {@code cef_content_setting_types_t} from CEF API 15100 and must not be reordered. Deprecated
 * values remain present because removing them would shift every later native value.
 */
public enum CefContentSettingType {
    COOKIES(0),
    IMAGES(1),
    JAVASCRIPT(2),
    POPUPS(3),
    GEOLOCATION(4),
    NOTIFICATIONS(5),
    AUTO_SELECT_CERTIFICATE(6),
    MIXEDSCRIPT(7),
    MEDIASTREAM_MIC(8),
    MEDIASTREAM_CAMERA(9),
    PROTOCOL_HANDLERS(10),
    DEPRECATED_PPAPI_BROKER(11),
    AUTOMATIC_DOWNLOADS(12),
    MIDI_SYSEX(13),
    SSL_CERT_DECISIONS(14),
    PROTECTED_MEDIA_IDENTIFIER(15),
    APP_BANNER(16),
    SITE_ENGAGEMENT(17),
    PERSISTENT_STORAGE(18),
    USB_CHOOSER_DATA(19),
    BLUETOOTH_GUARD(20),
    BACKGROUND_SYNC(21),
    AUTOPLAY(22),
    IMPORTANT_SITE_INFO(23),
    PERMISSION_AUTOBLOCKER_DATA(24),
    ADS(25),
    ADS_DATA(26),
    MIDI(27),
    PASSWORD_PROTECTION(28),
    MEDIA_ENGAGEMENT(29),
    SOUND(30),
    CLIENT_HINTS(31),
    SENSORS(32),
    DEPRECATED_ACCESSIBILITY_EVENTS(33),
    PAYMENT_HANDLER(34),
    USB_GUARD(35),
    BACKGROUND_FETCH(36),
    INTENT_PICKER_DISPLAY(37),
    IDLE_DETECTION(38),
    SERIAL_GUARD(39),
    SERIAL_CHOOSER_DATA(40),
    PERIODIC_BACKGROUND_SYNC(41),
    BLUETOOTH_SCANNING(42),
    HID_GUARD(43),
    HID_CHOOSER_DATA(44),
    WAKE_LOCK_SCREEN(45),
    WAKE_LOCK_SYSTEM(46),
    LEGACY_COOKIE_ACCESS(47),
    FILE_SYSTEM_WRITE_GUARD(48),
    NFC(49),
    BLUETOOTH_CHOOSER_DATA(50),
    CLIPBOARD_READ_WRITE(51),
    CLIPBOARD_SANITIZED_WRITE(52),
    SAFE_BROWSING_URL_CHECK_DATA(53),
    VR(54),
    AR(55),
    FILE_SYSTEM_READ_GUARD(56),
    STORAGE_ACCESS(57),
    CAMERA_PAN_TILT_ZOOM(58),
    WINDOW_MANAGEMENT(59),
    INSECURE_PRIVATE_NETWORK_DEPRECATED(60),
    LOCAL_FONTS(61),
    PERMISSION_AUTOREVOCATION_DATA(62),
    FILE_SYSTEM_LAST_PICKED_DIRECTORY(63),
    DISPLAY_CAPTURE(64),
    FILE_SYSTEM_ACCESS_CHOOSER_DATA(65),
    FEDERATED_IDENTITY_SHARING(66),
    JAVASCRIPT_JIT(67),
    HTTP_ALLOWED(68),
    FORMFILL_METADATA(69),
    DEPRECATED_FEDERATED_IDENTITY_ACTIVE_SESSION(70),
    AUTO_DARK_WEB_CONTENT(71),
    REQUEST_DESKTOP_SITE(72),
    FEDERATED_IDENTITY_API(73),
    NOTIFICATION_INTERACTIONS(74),
    REDUCED_ACCEPT_LANGUAGE(75),
    NOTIFICATION_PERMISSION_REVIEW(76),
    PRIVATE_NETWORK_GUARD_DEPRECATED(77),
    PRIVATE_NETWORK_CHOOSER_DATA_DEPRECATED(78),
    FEDERATED_IDENTITY_IDENTITY_PROVIDER_SIGNIN_STATUS(79),
    REVOKED_UNUSED_SITE_PERMISSIONS(80),
    TOP_LEVEL_STORAGE_ACCESS(81),
    FEDERATED_IDENTITY_AUTO_REAUTHN_PERMISSION(82),
    FEDERATED_IDENTITY_IDENTITY_PROVIDER_REGISTRATION(83),
    ANTI_ABUSE(84),
    THIRD_PARTY_STORAGE_PARTITIONING_DEPRECATED(85),
    HTTPS_ENFORCED(86),
    ALL_SCREEN_CAPTURE(87),
    COOKIE_CONTROLS_METADATA(88),
    TPCD_HEURISTICS_GRANTS_DEPRECATED(89),
    TPCD_METADATA_GRANTS_DEPRECATED(90),
    TPCD_TRIAL_DEPRECATED(91),
    TOP_LEVEL_TPCD_TRIAL_DEPRECATED(92),
    TOP_LEVEL_TPCD_ORIGIN_TRIAL_DEPRECATED(93),
    AUTO_PICTURE_IN_PICTURE(94),
    FILE_SYSTEM_ACCESS_EXTENDED_PERMISSION(95),
    FILE_SYSTEM_ACCESS_RESTORE_PERMISSION(96),
    CAPTURED_SURFACE_CONTROL(97),
    SMART_CARD_GUARD(98),
    SMART_CARD_DATA(99),
    WEB_PRINTING(100),
    AUTOMATIC_FULLSCREEN(101),
    SUB_APP_INSTALLATION_PROMPTS(102),
    SPEAKER_SELECTION(103),
    DIRECT_SOCKETS(104),
    KEYBOARD_LOCK(105),
    POINTER_LOCK(106),
    REVOKED_ABUSIVE_NOTIFICATION_PERMISSIONS(107),
    TRACKING_PROTECTION_DEPRECATED(108),
    DISPLAY_MEDIA_SYSTEM_AUDIO(109),
    JAVASCRIPT_OPTIMIZER(110),
    STORAGE_ACCESS_HEADER_ORIGIN_TRIAL(111),
    HAND_TRACKING(112),
    WEB_APP_INSTALLATION(113),
    DIRECT_SOCKETS_PRIVATE_NETWORK_ACCESS(114),
    LEGACY_COOKIE_SCOPE(115),
    ARE_SUSPICIOUS_NOTIFICATIONS_ALLOWLISTED_BY_USER(116),
    CONTROLLED_FRAME(117),
    REVOKED_DISRUPTIVE_NOTIFICATION_PERMISSIONS(118),
    LOCAL_NETWORK_ACCESS(119),
    ON_DEVICE_SPEECH_RECOGNITION_LANGUAGES_DOWNLOADED(120),
    INITIALIZED_TRANSLATIONS(121),
    SUSPICIOUS_NOTIFICATION_IDS(122),
    GEOLOCATION_WITH_OPTIONS(123),
    DEVICE_ATTRIBUTES(124),
    PERMISSION_ACTIONS_HISTORY(125),
    SUSPICIOUS_NOTIFICATION_SHOW_ORIGINAL(126),
    LOCAL_NETWORK(127),
    LOOPBACK_NETWORK(128),
    SUB_APPS_WITHOUT_PROMPTS(129),
    INLINE_CUE_MENU(130);

    private static final CefContentSettingType[] BY_VALUE = values();
    private final int value_;

    CefContentSettingType(int value) {
        value_ = value;
    }

    /** Returns the exact {@code cef_content_setting_types_t} integer value. */
    public int getValue() {
        return value_;
    }

    /** Returns the Java type for an exact native CEF API 15100 value. */
    public static CefContentSettingType fromValue(int value) {
        if (value < 0 || value >= BY_VALUE.length || BY_VALUE[value].value_ != value) {
            throw new IllegalArgumentException("Unknown CEF content setting type: " + value);
        }
        return BY_VALUE[value];
    }
}
