cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED DOWNLOAD_CEF_FILE)
  message(FATAL_ERROR "DOWNLOAD_CEF_FILE is required")
endif()
include("${DOWNLOAD_CEF_FILE}")

if(TEST_CASE STREQUAL "archive_paths")
  _cef_validate_archive_paths("${ARCHIVE_PATH}" "${DISTRIBUTION}" _valid _reason)
elseif(TEST_CASE STREQUAL "distribution")
  _cef_validate_distribution("${DISTRIBUTION_ROOT}" "${PLATFORM}" "${VERSION}" "${CHANNEL}" "${ARCHIVE_SHA1}" _valid _reason)
else()
  message(FATAL_ERROR "Unknown TEST_CASE='${TEST_CASE}'")
endif()

if(EXPECT_VALID)
  if(NOT _valid)
    message(FATAL_ERROR "Expected validation success, got: ${_reason}")
  endif()
else()
  if(_valid)
    message(FATAL_ERROR "Expected validation failure")
  endif()
  if(DEFINED EXPECT_REASON)
    string(FIND "${_reason}" "${EXPECT_REASON}" _reason_position)
    if(_reason_position EQUAL -1)
      message(FATAL_ERROR "Validation reason '${_reason}' does not contain '${EXPECT_REASON}'")
    endif()
  endif()
endif()
