/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_CefApp */

#ifndef _Included_org_cef_CefApp
#define _Included_org_cef_CefApp
#ifdef __cplusplus
extern "C" {
#endif
#undef org_cef_CefApp_SHUTDOWN_WAIT_SECONDS
#define org_cef_CefApp_SHUTDOWN_WAIT_SECONDS 30LL
#undef org_cef_CefApp_SHUTDOWN_PUMP_DELAY_MILLIS
#define org_cef_CefApp_SHUTDOWN_PUMP_DELAY_MILLIS 10LL
#undef org_cef_CefApp_AWT_MESSAGE_PUMP_FALLBACK_FPS
#define org_cef_CefApp_AWT_MESSAGE_PUMP_FALLBACK_FPS 120L
/*
 * Class:     org_cef_CefApp
 * Method:    N_Startup
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_CefApp_N_1Startup
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_cef_CefApp
 * Method:    N_PreInitialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_CefApp_N_1PreInitialize
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_Initialize
 * Signature: (Lorg/cef/handler/CefAppHandler;Lorg/cef/CefSettings;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_CefApp_N_1Initialize
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_AbortInitialization
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_CefApp_N_1AbortInitialization
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_Shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_CefApp_N_1Shutdown
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_DoMessageLoopWorkNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_CefApp_N_1DoMessageLoopWorkNative
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_GetVersion
 * Signature: ()Lorg/cef/CefApp/CefVersion;
 */
JNIEXPORT jobject JNICALL Java_org_cef_CefApp_N_1GetVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_GetLogSeverityForTesting
 * Signature: (Lorg/cef/CefSettings;)I
 */
JNIEXPORT jint JNICALL Java_org_cef_CefApp_N_1GetLogSeverityForTesting
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_RegisterSchemeHandlerFactory
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/cef/callback/CefSchemeHandlerFactory;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_CefApp_N_1RegisterSchemeHandlerFactory
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     org_cef_CefApp
 * Method:    N_ClearSchemeHandlerFactories
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_CefApp_N_1ClearSchemeHandlerFactories
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
