/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefBinaryValue_N */

#ifndef _Included_org_cef_callback_CefBinaryValue_N
#define _Included_org_cef_callback_CefBinaryValue_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefBinaryValue_N
 * Method:    N_Create
 * Signature: ([BII)Lorg/cef/callback/CefBinaryValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefBinaryValue_1N_N_1Create
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     org_cef_callback_CefBinaryValue_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefBinaryValue_1N_N_1Dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefBinaryValue_N
 * Method:    N_IsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefBinaryValue_1N_N_1IsValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefBinaryValue_N
 * Method:    N_IsOwned
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefBinaryValue_1N_N_1IsOwned
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefBinaryValue_N
 * Method:    N_IsSame
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefBinaryValue_1N_N_1IsSame
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_cef_callback_CefBinaryValue_N
 * Method:    N_IsEqual
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefBinaryValue_1N_N_1IsEqual
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_cef_callback_CefBinaryValue_N
 * Method:    N_Copy
 * Signature: (J)Lorg/cef/callback/CefBinaryValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefBinaryValue_1N_N_1Copy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefBinaryValue_N
 * Method:    N_GetSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_cef_callback_CefBinaryValue_1N_N_1GetSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefBinaryValue_N
 * Method:    N_GetData
 * Signature: (J[BIIJ)I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefBinaryValue_1N_N_1GetData
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
