/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_browser_CefBrowser_N */

#ifndef _Included_org_cef_browser_CefBrowser_N
#define _Included_org_cef_browser_CefBrowser_N
#ifdef __cplusplus
extern "C" {
#endif
#undef org_cef_browser_CefBrowser_N_BOOLEAN_QUERY_FAILED
#define org_cef_browser_CefBrowser_N_BOOLEAN_QUERY_FAILED -1L
#undef org_cef_browser_CefBrowser_N_BOOLEAN_QUERY_FALSE
#define org_cef_browser_CefBrowser_N_BOOLEAN_QUERY_FALSE 0L
#undef org_cef_browser_CefBrowser_N_BOOLEAN_QUERY_TRUE
#define org_cef_browser_CefBrowser_N_BOOLEAN_QUERY_TRUE 1L
/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ConvertBrowserSettingsForTesting
 * Signature: (Lorg/cef/CefBrowserSettings;ZZ)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ConvertBrowserSettingsForTesting
  (JNIEnv *, jclass, jobject, jboolean, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ConvertImeCompositionForTesting
 * Signature: (Ljava/lang/String;[Lorg/cef/input/CefCompositionUnderline;Lorg/cef/misc/CefRange;Lorg/cef/misc/CefRange;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ConvertImeCompositionForTesting
  (JNIEnv *, jclass, jstring, jobjectArray, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_IsOnCefUiThreadForTesting
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1IsOnCefUiThreadForTesting
  (JNIEnv *, jclass);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ResolveLinuxNativeKeyCodeForTesting
 * Signature: (JIIZZ)I
 */
JNIEXPORT jint JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ResolveLinuxNativeKeyCodeForTesting
  (JNIEnv *, jclass, jlong, jint, jint, jboolean, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ResolveWindowsNativeKeyCodeForTesting
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ResolveWindowsNativeKeyCodeForTesting
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_CreateBrowser
 * Signature: (Lorg/cef/handler/CefClientHandler;JLjava/lang/String;ZZLjava/awt/Component;Lorg/cef/browser/CefRequestContext;Lorg/cef/CefBrowserSettings;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1CreateBrowser
  (JNIEnv *, jobject, jobject, jlong, jstring, jboolean, jboolean, jobject, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_CreateDevTools
 * Signature: (Lorg/cef/browser/CefBrowser;Lorg/cef/handler/CefClientHandler;JZZLjava/awt/Component;Ljava/awt/Point;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1CreateDevTools
  (JNIEnv *, jobject, jobject, jobject, jlong, jboolean, jboolean, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ExecuteDevToolsMethod
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/cef/browser/CefBrowser_N/IntCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ExecuteDevToolsMethod
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_AddDevToolsMessageObserver
 * Signature: (Lorg/cef/browser/CefDevToolsMessageObserver;)Lorg/cef/browser/CefRegistration;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefBrowser_1N_N_1AddDevToolsMessageObserver
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetWindowHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetWindowHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_IsValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1IsValid
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_CanGoBack
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1CanGoBack
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GoBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GoBack
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_CanGoForward
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1CanGoForward
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GoForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GoForward
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_IsLoading
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1IsLoading
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_Reload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1Reload
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ReloadIgnoreCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ReloadIgnoreCache
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_StopLoad
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1StopLoad
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetIdentifier
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetIdentifier
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_IsSame
 * Signature: (Lorg/cef/browser/CefBrowser;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1IsSame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetMainFrame
 * Signature: ()Lorg/cef/browser/CefFrame;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetMainFrame
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetFocusedFrame
 * Signature: ()Lorg/cef/browser/CefFrame;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetFocusedFrame
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetFrameByIdentifier
 * Signature: (Ljava/lang/String;)Lorg/cef/browser/CefFrame;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetFrameByIdentifier
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetFrameByName
 * Signature: (Ljava/lang/String;)Lorg/cef/browser/CefFrame;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetFrameByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetFrameIdentifiers
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetFrameIdentifiers
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetFrameNames
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetFrameNames
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetFrameCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetFrameCount
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_IsPopup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1IsPopup
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_HasDocument
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1HasDocument
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ViewSource
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ViewSource
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetSource
 * Signature: (Lorg/cef/callback/CefStringVisitor;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetSource
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetText
 * Signature: (Lorg/cef/callback/CefStringVisitor;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetText
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_LoadRequest
 * Signature: (Lorg/cef/network/CefRequest;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1LoadRequest
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_LoadURL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1LoadURL
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ExecuteJavaScript
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ExecuteJavaScript
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetURL
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_IsWindowRenderingDisabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_browser_CefBrowser_1N_N_1IsWindowRenderingDisabled
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_Close
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1Close
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SetFocus
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SetFocus
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ImeSetComposition
 * Signature: (Ljava/lang/String;[Lorg/cef/input/CefCompositionUnderline;Lorg/cef/misc/CefRange;Lorg/cef/misc/CefRange;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ImeSetComposition
  (JNIEnv *, jobject, jstring, jobjectArray, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ImeCommitText
 * Signature: (Ljava/lang/String;Lorg/cef/misc/CefRange;I)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ImeCommitText
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ImeFinishComposingText
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ImeFinishComposingText
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ImeCancelComposition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ImeCancelComposition
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SetWindowVisibility
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SetWindowVisibility
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_NotifyScreenInfoChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1NotifyScreenInfoChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_CanZoom
 * Signature: (ILorg/cef/browser/CefBrowser_N/IntCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1CanZoom
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_Zoom
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1Zoom
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetDefaultZoomLevel
 * Signature: (Lorg/cef/browser/CefBrowser_N/DoubleCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetDefaultZoomLevel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetZoomLevel
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetZoomLevel
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetZoomLevelAsync
 * Signature: (Lorg/cef/browser/CefBrowser_N/DoubleCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetZoomLevelAsync
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SetZoomLevel
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SetZoomLevel
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_RunFileDialog
 * Signature: (Lorg/cef/handler/CefDialogHandler/FileDialogMode;Ljava/lang/String;Ljava/lang/String;Ljava/util/Vector;ILorg/cef/callback/CefRunFileDialogCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1RunFileDialog
  (JNIEnv *, jobject, jobject, jstring, jstring, jobject, jint, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_StartDownload
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1StartDownload
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_Print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1Print
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_PrintToPDF
 * Signature: (Ljava/lang/String;Lorg/cef/misc/CefPdfPrintSettings;Lorg/cef/callback/CefPdfPrintCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1PrintToPDF
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_Find
 * Signature: (Ljava/lang/String;ZZZ)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1Find
  (JNIEnv *, jobject, jstring, jboolean, jboolean, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_StopFinding
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1StopFinding
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ShowDevTools
 * Signature: (Ljava/awt/Point;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ShowDevTools
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_CloseDevTools
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1CloseDevTools
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ReplaceMisspelling
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ReplaceMisspelling
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_WasResized
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1WasResized
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_Invalidate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1Invalidate
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_InvalidatePaintElement
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1InvalidatePaintElement
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SendCaptureLostEvent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SendCaptureLostEvent
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SendKeyEvent
 * Signature: (Lorg/cef/event/CefKeyEvent;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SendKeyEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SendKeyEventAwt
 * Signature: (Ljava/awt/event/KeyEvent;Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SendKeyEventAwt
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SendMouseEvent
 * Signature: (Lorg/cef/event/CefMouseEvent;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SendMouseEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SendMouseEventAwt
 * Signature: (Ljava/awt/event/MouseEvent;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SendMouseEventAwt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SendMouseWheelEvent
 * Signature: (Lorg/cef/event/CefMouseWheelEvent;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SendMouseWheelEvent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SendMouseWheelEventAwt
 * Signature: (Ljava/awt/event/MouseWheelEvent;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SendMouseWheelEventAwt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_DragTargetDragEnter
 * Signature: (Lorg/cef/callback/CefDragData;Ljava/awt/Point;II)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1DragTargetDragEnter
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_DragTargetDragOver
 * Signature: (Ljava/awt/Point;II)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1DragTargetDragOver
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_DragTargetDragLeave
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1DragTargetDragLeave
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_DragTargetDrop
 * Signature: (Ljava/awt/Point;I)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1DragTargetDrop
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_DragSourceEndedAt
 * Signature: (Ljava/awt/Point;I)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1DragSourceEndedAt
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_DragSourceSystemDragEnded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1DragSourceSystemDragEnded
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_UpdateUI
 * Signature: (Ljava/awt/Rectangle;Ljava/awt/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1UpdateUI
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SetParent
 * Signature: (JLjava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SetParent
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_NotifyMoveOrResizeStarted
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1NotifyMoveOrResizeStarted
  (JNIEnv *, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SetWindowlessFrameRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SetWindowlessFrameRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_GetWindowlessFrameRate
 * Signature: (Lorg/cef/browser/CefBrowser_N/IntCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1GetWindowlessFrameRate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_SetAudioMuted
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1SetAudioMuted
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_IsAudioMuted
 * Signature: (Lorg/cef/browser/CefBrowser_N/IntCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1IsAudioMuted
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_IsFullscreen
 * Signature: (Lorg/cef/browser/CefBrowser_N/IntCallback;)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1IsFullscreen
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_cef_browser_CefBrowser_N
 * Method:    N_ExitFullscreen
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cef_browser_CefBrowser_1N_N_1ExitFullscreen
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
