/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefDictionaryValue_N */

#ifndef _Included_org_cef_callback_CefDictionaryValue_N
#define _Included_org_cef_callback_CefDictionaryValue_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_Create
 * Signature: ()Lorg/cef/callback/CefDictionaryValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1Create
  (JNIEnv *, jclass);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1Dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_IsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1IsValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_IsOwned
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1IsOwned
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_IsReadOnly
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1IsReadOnly
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_IsSame
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1IsSame
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_IsEqual
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1IsEqual
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_Copy
 * Signature: (JZ)Lorg/cef/callback/CefDictionaryValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1Copy
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_Clear
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1Clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_HasKey
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1HasKey
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetKeys
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetKeys
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_Remove
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1Remove
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetType
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetType
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetValue
 * Signature: (JLjava/lang/String;)Lorg/cef/callback/CefValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetValue
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetBool
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetBool
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetInt
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetInt
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetDouble
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetDouble
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetString
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetBinary
 * Signature: (JLjava/lang/String;)Lorg/cef/callback/CefBinaryValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetBinary
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetDictionary
 * Signature: (JLjava/lang/String;)Lorg/cef/callback/CefDictionaryValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetDictionary
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_GetList
 * Signature: (JLjava/lang/String;)Lorg/cef/callback/CefListValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1GetList
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_SetValue
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1SetValue
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_SetNull
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1SetNull
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_SetBool
 * Signature: (JLjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1SetBool
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_SetInt
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1SetInt
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_SetDouble
 * Signature: (JLjava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1SetDouble
  (JNIEnv *, jobject, jlong, jstring, jdouble);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_SetString
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1SetString
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_SetBinary
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1SetBinary
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_SetDictionary
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1SetDictionary
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_cef_callback_CefDictionaryValue_N
 * Method:    N_SetList
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefDictionaryValue_1N_N_1SetList
  (JNIEnv *, jobject, jlong, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
