/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefResourceReadCallback_N */

#ifndef _Included_org_cef_callback_CefResourceReadCallback_N
#define _Included_org_cef_callback_CefResourceReadCallback_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefResourceReadCallback_N
 * Method:    N_Continue
 * Signature: (JIJ[B)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefResourceReadCallback_1N_N_1Continue
  (JNIEnv *, jobject, jlong, jint, jlong, jbyteArray);

/*
 * Class:     org_cef_callback_CefResourceReadCallback_N
 * Method:    N_TestSetupCallForTesting
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefResourceReadCallback_1N_N_1TestSetupCallForTesting
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_cef_callback_CefResourceReadCallback_N
 * Method:    N_TestOpenCallbackRetentionForTesting
 * Signature: (ZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefResourceReadCallback_1N_N_1TestOpenCallbackRetentionForTesting
  (JNIEnv *, jclass, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
