/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cef_callback_CefValue_N */

#ifndef _Included_org_cef_callback_CefValue_N
#define _Included_org_cef_callback_CefValue_N
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_Create
 * Signature: ()Lorg/cef/callback/CefValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefValue_1N_N_1Create
  (JNIEnv *, jclass);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cef_callback_CefValue_1N_N_1Dispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_IsValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1IsValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_IsOwned
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1IsOwned
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_IsReadOnly
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1IsReadOnly
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_IsSame
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1IsSame
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_IsEqual
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1IsEqual
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_Copy
 * Signature: (J)Lorg/cef/callback/CefValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefValue_1N_N_1Copy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_GetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefValue_1N_N_1GetType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_GetBool
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1GetBool
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_GetInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_cef_callback_CefValue_1N_N_1GetInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_GetDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_cef_callback_CefValue_1N_N_1GetDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_GetString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cef_callback_CefValue_1N_N_1GetString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_GetBinary
 * Signature: (J)Lorg/cef/callback/CefBinaryValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefValue_1N_N_1GetBinary
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_GetDictionary
 * Signature: (J)Lorg/cef/callback/CefDictionaryValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefValue_1N_N_1GetDictionary
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_GetList
 * Signature: (J)Lorg/cef/callback/CefListValue_N;
 */
JNIEXPORT jobject JNICALL Java_org_cef_callback_CefValue_1N_N_1GetList
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_SetNull
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1SetNull
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_SetBool
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1SetBool
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_SetInt
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1SetInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_SetDouble
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1SetDouble
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_SetString
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1SetString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_SetBinary
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1SetBinary
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_SetDictionary
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1SetDictionary
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_cef_callback_CefValue_N
 * Method:    N_SetList
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_cef_callback_CefValue_1N_N_1SetList
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
